# Generated by Django 5.1.5 on 2025-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='html_file_path',
            field=models.CharField(default='', help_text='Path to the stored HTML file', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapedcontent',
            name='html_content',
            field=models.TextField(help_text='Preview of the HTML content'),
        ),
    ]
