# Generated by Django 5.1.5 on 2025-01-20 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapedcontent_html_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('endpoint_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scraper.scrapingjob')),
            ],
            options={
                'unique_together': {('job', 'url')},
            },
        ),
    ]
