# Generated by Django 5.1.5 on 2025-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_websiteendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='excluded_patterns',
            field=models.TextField(blank=True, default='', help_text='Comma-separated patterns to exclude from scraping (e.g., /login/, /admin/)'),
        ),
    ]
