# Generated by Django 5.1.5 on 2025-01-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapingjob_excluded_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingjob',
            name='excluded_patterns',
        ),
    ]
