# Generated by Django 5.1.5 on 2025-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilematch',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
