# Generated by Django 5.1.5 on 2025-01-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0003_person_profile_searchhistory_delete_profilematch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-confidence_score', '-last_updated']},
        ),
        migrations.AddField(
            model_name='profile',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
    ]
